defmodule Scopestrength.Programmes do
  @moduledoc """
  The Programmes context.
  """

  import Ecto.Query, warn: false
  alias Scopestrength.Repo

  alias Scopestrength.Programmes.Programme


 def get_programme_with_template(id) do
   Programme|> Repo.get(id)|>
   Repo.preload(programmeTemplates: [programmeDetails: [exercise: :muscle]])
 end

 @doc """
 Calculates total volume (direct and effective) across all templates in a programme.
 Returns a map of muscle groups with their direct and effective sets.
 """
 def calculate_programme_volume(programme) do
   alias Scopestrength.Exercises.ExerciseMuscleContribution

   # Get all exercise IDs across all templates
   exercise_ids =
     programme.programmeTemplates
     |> Enum.flat_map(& &1.programmeDetails)
     |> Enum.map(& &1.exercise_id)
     |> Enum.uniq()

   # Load muscle contributions for all exercises
   muscle_contributions =
     Repo.all(from c in ExerciseMuscleContribution, where: c.exercise_id in ^exercise_ids)
     |> Repo.preload(:muscle)

   # Group contributions by exercise_id for faster lookup
   contributions_by_exercise = Enum.group_by(muscle_contributions, & &1.exercise_id)

   # Expand all programme details across all templates into muscle contributions
   expanded =
     programme.programmeTemplates
     |> Enum.flat_map(fn template ->
       template.programmeDetails
       |> Enum.flat_map(fn detail ->
         sets = String.to_integer(detail.set)
         contributions = Map.get(contributions_by_exercise, detail.exercise_id, [])

         Enum.map(contributions, fn c ->
           {c.muscle.name, c.role, sets * c.multiplier}
         end)
       end)
     end)

   # Group by muscle and calculate direct/effective volume
   expanded
   |> Enum.group_by(fn {muscle, _role, _volume} -> muscle end)
   |> Enum.map(fn {muscle, rows} ->
     direct_sets =
       rows
       |> Enum.filter(fn {_m, role, _v} -> role == "primary" end)
       |> Enum.map(fn {_m, _r, v} -> v end)
       |> Enum.sum()

     effective_sets =
       rows
       |> Enum.map(fn {_m, _r, v} -> v end)
       |> Enum.sum()

     {muscle, %{direct: direct_sets, effective: effective_sets}}
   end)
   |> Map.new()
 end

  def clone_programme(user_id, programme_id) do

    # 1. One query: the programme row itself (id, name, description, user_id).
    #    Associations come back as NotLoaded — Ecto never lazy-loads.
    #
    #    Scoped by user_id so a crafted phx-value-id cannot clone someone
    #    else's programme. Raises Ecto.NoResultsError if it isn't yours,
    #    which leaks nothing about whether the id exists.
    programme =
      Repo.get_by!(Programme, id: programme_id, user_id: user_id)
      # 2. Two more queries, one per level of nesting: all templates, then ALL
      #    details in a single WHERE programme_template_id = ANY($1). Six
      #    templates still means one details query, not six.
      #
      #    3 round trips total, and flat — a 3-day programme and a 60-day one
      #    both cost 3. The reads are already batched; the writes below are not.
      |> Repo.preload(programmeTemplates: :programmeDetails)

    # 3. BEGIN — one round trip. Everything below is atomic: a failure at any
    #    point rolls back every insert before it, so you never end up with a
    #    programme that has 4 of its 6 templates. Non-negotiable here.
    #
    #    Returns normally -> COMMIT, {:ok, new_programme}.
    #    Raises or Repo.rollback/1 -> ROLLBACK, {:error, reason}.
    #
    #    The transaction is pinned to ONE pooled connection, so spawning the
    #    inserts across processes would put them on other connections and
    #    silently break the rollback. Batching is the only safe speedup.
    Repo.transaction(fn ->
      # 4. One INSERT — the new parent programme row.
      {:ok, new_programme} =
        create_programme(%{
          name: "#{programme.name} (copy)",
          description: programme.description,
          user_id: programme.user_id
        })

      # insert_all skips changesets, so timestamps are not autogenerated.
      # Both tables have NOT NULL timestamps, so set them by hand.
      now = DateTime.utc_now() |> DateTime.truncate(:second)

      # 5. ONE insert for every template, not one per template.
      #    returning: [:id] hands back the new ids in the same round trip.
      #    The pinned count is the pattern match: a short insert raises and
      #    rolls back, and it guards the zip below from pairing against a
      #    truncated list and silently dropping details.
      template_rows =
        Enum.map(programme.programmeTemplates, fn template ->
          %{
            name: template.name,
            programme_id: new_programme.id,
            inserted_at: now,
            updated_at: now
          }
        end)

      template_count = length(template_rows)

      {^template_count, inserted_templates} =
        Repo.insert_all(Scopestrength.Programmes.ProgrammeTemplate, template_rows,
          returning: [:id]
        )

      # 6. Pair each OLD template with its NEW id positionally — insert_all
      #    returns rows in the order they were passed. Then flatten every
      #    template's details into one list. Pure in-memory work: flat_map
      #    builds the list, it does not touch the database.
      detail_rows =
        Enum.zip(programme.programmeTemplates, inserted_templates)
        |> Enum.flat_map(fn {old_template, new_template} ->
          Enum.map(old_template.programmeDetails, fn detail ->
            %{
              set: detail.set,
              reps: detail.reps,
              rir: detail.rir,
              exercise_id: detail.exercise_id,
              programme_template_id: new_template.id,
              inserted_at: now,
              updated_at: now
            }
          end)
        end)

      # 7. ONE insert for ALL details across ALL templates — replaces the 36+
      #    nested inserts. Same count assertion.
      #
      #    Postgres caps a statement at 65535 bind parameters; at 7 columns
      #    that is ~9000 rows, well above any real programme. chunk_every/2
      #    is the fix if that ever changes.
      detail_count = length(detail_rows)

      {^detail_count, _} =
        Repo.insert_all(Scopestrength.Programmes.ProgrammeDetails, detail_rows)

      new_programme
    end)
  end

  @doc """
  Returns the list of programme.

  ## Examples

      iex> list_programme()
      [%Programme{}, ...]

  """



  def list_programme do
    Repo.all(Programme)
  end

  @doc """
  Lists only the programmes belonging to `user_id`.

  Filters in SQL rather than loading every programme in the table and
  rejecting in Elixir.
  """
  def list_user_programmes(user_id) do
    Repo.all(from p in Programme, where: p.user_id == ^user_id)
  end

  @doc """
  Fetches a programme only if it belongs to `user_id`.

  Raises `Ecto.NoResultsError` when the programme does not exist OR belongs
  to another user — the two cases are deliberately indistinguishable.
  """
  def get_user_programme!(user_id, id) do
    Repo.get_by!(Programme, id: id, user_id: user_id)
  end

  @doc """
  Gets a single programme.

  Raises `Ecto.NoResultsError` if the Programme does not exist.

  ## Examples

      iex> get_programme!(123)
      %Programme{}

      iex> get_programme!(456)
      ** (Ecto.NoResultsError)

  """
  def get_programme!(id), do: Repo.get!(Programme, id)




  @doc """
  Creates a programme.

  ## Examples

      iex> create_programme(%{field: value})
      {:ok, %Programme{}}

      iex> create_programme(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_programme(attrs \\ %{}) do
    %Programme{}
    |> Programme.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a programme.

  ## Examples

      iex> update_programme(programme, %{field: new_value})
      {:ok, %Programme{}}

      iex> update_programme(programme, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """





  def update_programme(%Programme{} = programme, attrs) do
    programme
    |> Programme.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a programme.

  ## Examples

      iex> delete_programme(programme)
      {:ok, %Programme{}}

      iex> delete_programme(programme)
      {:error, %Ecto.Changeset{}}

  """
  def delete_programme(%Programme{} = programme) do
    Repo.delete(programme)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking programme changes.

  ## Examples

      iex> change_programme(programme)
      %Ecto.Changeset{data: %Programme{}}

  """
  def change_programme(%Programme{} = programme, attrs \\ %{}) do
    Programme.changeset(programme, attrs)
  end

  alias Scopestrength.Programmes.ProgrammeDetails

  @doc """
  Returns the list of programme_details.

  ## Examples

      iex> list_programme_details()
      [%ProgrammeDetails{}, ...]

  """
  def list_programme_details do
    Repo.all(ProgrammeDetails)
  end

  @doc """
  Gets a single programme_details.

  Raises `Ecto.NoResultsError` if the Programme details does not exist.

  ## Examples

      iex> get_programme_details!(123)
      %ProgrammeDetails{}

      iex> get_programme_details!(456)
      ** (Ecto.NoResultsError)

  """
  def get_programme_details!(id), do: Repo.get!(ProgrammeDetails, id)

  def get_programme_detail_with_exericse!(id) do
    Repo.get!(ProgrammeDetails,id)
    |> Repo.preload(:exercise)
  end

  @spec create_programme_details() :: any()
  @doc """
  Creates a programme_details.

  ## Examples

      iex> create_programme_details(%{field: value})
      {:ok, %ProgrammeDetails{}}

      iex> create_programme_details(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_programme_details(attrs \\ %{}) do
    %ProgrammeDetails{}
    |> ProgrammeDetails.changeset(attrs)
    |> Repo.insert()

  end

  @doc """
  Updates a programme_details.

  ## Examples

      iex> update_programme_details(programme_details, %{field: new_value})
      {:ok, %ProgrammeDetails{}}

      iex> update_programme_details(programme_details, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_programme_details(%ProgrammeDetails{} = programme_details, attrs) do
    programme_details
    |> ProgrammeDetails.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a programme_details.

  ## Examples

      iex> delete_programme_details(programme_details)
      {:ok, %ProgrammeDetails{}}

      iex> delete_programme_details(programme_details)
      {:error, %Ecto.Changeset{}}

  """
  def delete_programme_details(%ProgrammeDetails{} = programme_details) do
    Repo.delete(programme_details)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking programme_details changes.

  ## Examples

      iex> change_programme_details(programme_details)
      %Ecto.Changeset{data: %ProgrammeDetails{}}

  """
  def change_programme_details(%ProgrammeDetails{} = programme_details, attrs \\ %{}) do
    ProgrammeDetails.changeset(programme_details, attrs)
  end

  alias Scopestrength.Programmes.ProgrammeTemplate

  @doc """
  Returns the list of programme_template.

  ## Examples

      iex> list_programme_template()
      [%ProgrammeTemplate{}, ...]

  """
  def list_programme_template do
    Repo.all(ProgrammeTemplate)
  end


  @doc """
  Gets a single programme_template.

  Raises `Ecto.NoResultsError` if the Programme template does not exist.

  ## Examples

      iex> get_programme_template!(123)
      %ProgrammeTemplate{}

      iex> get_programme_template!(456)
      ** (Ecto.NoResultsError)

  """
  def get_programme_template!(id), do: Repo.get!(ProgrammeTemplate, id)

  @doc """
  Creates a programme_template.

  ## Examples

      iex> create_programme_template(%{field: value})
      {:ok, %ProgrammeTemplate{}}

      iex> create_programme_template(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_programme_template(attrs \\ %{}) do
    %ProgrammeTemplate{}
    |> ProgrammeTemplate.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a programme_template.

  ## Examples

      iex> update_programme_template(programme_template, %{field: new_value})
      {:ok, %ProgrammeTemplate{}}

      iex> update_programme_template(programme_template, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_programme_template(%ProgrammeTemplate{} = programme_template, attrs) do
    programme_template
    |> ProgrammeTemplate.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a programme_template.

  ## Examples

      iex> delete_programme_template(programme_template)
      {:ok, %ProgrammeTemplate{}}

      iex> delete_programme_template(programme_template)
      {:error, %Ecto.Changeset{}}

  """
  def delete_programme_template(%ProgrammeTemplate{} = programme_template) do
    Repo.delete(programme_template)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking programme_template changes.

  ## Examples

      iex> change_programme_template(programme_template)
      %Ecto.Changeset{data: %ProgrammeTemplate{}}

  """
  def change_programme_template(%ProgrammeTemplate{} = programme_template, attrs \\ %{}) do
    ProgrammeTemplate.changeset(programme_template, attrs)
  end

  alias Scopestrength.Programmes.ProgrammeUser

  @doc """
  Returns the list of programmeuser.

  ## Examples

      iex> list_programmeuser()
      [%ProgrammeUser{}, ...]

  """
  def list_programmeuser do
    Repo.all(ProgrammeUser)
  end

  @doc """
  Gets a single programme_user.

  Raises `Ecto.NoResultsError` if the Programme user does not exist.

  ## Examples

      iex> get_programme_user!(123)
      %ProgrammeUser{}

      iex> get_programme_user!(456)
      ** (Ecto.NoResultsError)

  """
  def get_programme_user!(id), do: Repo.get!(ProgrammeUser, id)

  @doc """
  Creates a programme_user.

  ## Examples

      iex> create_programme_user(%{field: value})
      {:ok, %ProgrammeUser{}}

      iex> create_programme_user(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_programme_user(attrs \\ %{}) do
    %ProgrammeUser{}
    |> ProgrammeUser.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a programme_user.

  ## Examples

      iex> update_programme_user(programme_user, %{field: new_value})
      {:ok, %ProgrammeUser{}}

      iex> update_programme_user(programme_user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_programme_user(%ProgrammeUser{} = programme_user, attrs) do
    programme_user
    |> ProgrammeUser.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a programme_user.

  ## Examples

      iex> delete_programme_user(programme_user)
      {:ok, %ProgrammeUser{}}

      iex> delete_programme_user(programme_user)
      {:error, %Ecto.Changeset{}}

  """
  def delete_programme_user(%ProgrammeUser{} = programme_user) do
    Repo.delete(programme_user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking programme_user changes.

  ## Examples

      iex> change_programme_user(programme_user)
      %Ecto.Changeset{data: %ProgrammeUser{}}

  """
  def change_programme_user(%ProgrammeUser{} = programme_user, attrs \\ %{}) do
    ProgrammeUser.changeset(programme_user, attrs)
  end
end
